dist: xenial
language: ruby
cache: bundler

before_install:
  # rubygems 2.7.8 and greater include bundler, leave 2.6.0 untouched
  - |
    rv="$(ruby -e 'STDOUT.write RUBY_VERSION')";
    if   [ "$rv" \< "2.3" ]; then gem update --system 2.7.8 --no-document
    elif [ "$rv" \< "2.6" ]; then gem update --system --no-document --conservative
    fi
  - ruby -v && gem --version && bundle version

before_script:
  - bundle exec rake compile

script:
  - bundle exec rake

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6
  - ruby-head

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      env: RUBYOPT="--jit"
    - rvm: 2.3.8
      os: osx
    - rvm: 2.5.3
      os: osx
    - rvm: jruby-9.2.5.0
      dist: trusty
      sudo: false
    - rvm: jruby-head
      dist: trusty
      sudo: false

  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head
      env: RUBYOPT="--jit"
    - rvm: jruby-head
      dist: trusty
      sudo: false

env:
  global:
    - TESTOPTS="-v"
